---
title: 刘正青的博客
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
permalink: "/:year-:month-:day-:title/"
paginate: 10
markdown: kramdown
encoding: utf-8
author:
  name: 刘正青
  email: liuzq7@gmail.com
  link: 
  weibo: 
  github: https://github.com/zk4
  zhihu: 
  juejin: 
  stackoverflow: 
description: 
url: https://zk4.github.io
repo: https://github.com/zk4
rss: "/pages/atom.xml"
gavatar: "/public/img/gavatar.jpg"
favicon: "/public/img/favicon.ico"

# disqus:
#   shortname: gotoshare

comments:
  gitalk: true
  gitalk_clientID: '2bdaa3cadb84736bd481'
  gitalk_secret: '2bf4b2d010688d3fc06defef1ea63292f44baed3'
  gitalk_repo: 'blog-comment'
  gitalk_owner: 'zk4'
  gitalk_admin: 'zk4'
  distractionFreeMode: true
 
active: 前端
cates:
- React
- PKM
locals:
  ideas: 想法
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
  search: 搜索
gems:
- jekyll-sitemap
- jekyll-paginate
- jekyll/tagging
- jekyll-tagging-related_posts
- jekyll-seo-tag
- jekyll-mermaid
exclude:
- ".idea/"
- ".github/"
- ".travis/"
- node_modules/
- themes/
- _posts/演讲/assets
